require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HowtolistsController do

  # This should return the minimal set of attributes required to create a valid
  # Howtolist. As you add validations to Howtolist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HowtolistsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all howtolists as @howtolists" do
      howtolist = Howtolist.create! valid_attributes
      get :index, {}, valid_session
      assigns(:howtolists).should eq([howtolist])
    end
  end

  describe "GET show" do
    it "assigns the requested howtolist as @howtolist" do
      howtolist = Howtolist.create! valid_attributes
      get :show, {:id => howtolist.to_param}, valid_session
      assigns(:howtolist).should eq(howtolist)
    end
  end

  describe "GET new" do
    it "assigns a new howtolist as @howtolist" do
      get :new, {}, valid_session
      assigns(:howtolist).should be_a_new(Howtolist)
    end
  end

  describe "GET edit" do
    it "assigns the requested howtolist as @howtolist" do
      howtolist = Howtolist.create! valid_attributes
      get :edit, {:id => howtolist.to_param}, valid_session
      assigns(:howtolist).should eq(howtolist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Howtolist" do
        expect {
          post :create, {:howtolist => valid_attributes}, valid_session
        }.to change(Howtolist, :count).by(1)
      end

      it "assigns a newly created howtolist as @howtolist" do
        post :create, {:howtolist => valid_attributes}, valid_session
        assigns(:howtolist).should be_a(Howtolist)
        assigns(:howtolist).should be_persisted
      end

      it "redirects to the created howtolist" do
        post :create, {:howtolist => valid_attributes}, valid_session
        response.should redirect_to(Howtolist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved howtolist as @howtolist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Howtolist.any_instance.stub(:save).and_return(false)
        post :create, {:howtolist => { "title" => "invalid value" }}, valid_session
        assigns(:howtolist).should be_a_new(Howtolist)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Howtolist.any_instance.stub(:save).and_return(false)
        post :create, {:howtolist => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested howtolist" do
        howtolist = Howtolist.create! valid_attributes
        # Assuming there are no other howtolists in the database, this
        # specifies that the Howtolist created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Howtolist.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => howtolist.to_param, :howtolist => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested howtolist as @howtolist" do
        howtolist = Howtolist.create! valid_attributes
        put :update, {:id => howtolist.to_param, :howtolist => valid_attributes}, valid_session
        assigns(:howtolist).should eq(howtolist)
      end

      it "redirects to the howtolist" do
        howtolist = Howtolist.create! valid_attributes
        put :update, {:id => howtolist.to_param, :howtolist => valid_attributes}, valid_session
        response.should redirect_to(howtolist)
      end
    end

    describe "with invalid params" do
      it "assigns the howtolist as @howtolist" do
        howtolist = Howtolist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Howtolist.any_instance.stub(:save).and_return(false)
        put :update, {:id => howtolist.to_param, :howtolist => { "title" => "invalid value" }}, valid_session
        assigns(:howtolist).should eq(howtolist)
      end

      it "re-renders the 'edit' template" do
        howtolist = Howtolist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Howtolist.any_instance.stub(:save).and_return(false)
        put :update, {:id => howtolist.to_param, :howtolist => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested howtolist" do
      howtolist = Howtolist.create! valid_attributes
      expect {
        delete :destroy, {:id => howtolist.to_param}, valid_session
      }.to change(Howtolist, :count).by(-1)
    end

    it "redirects to the howtolists list" do
      howtolist = Howtolist.create! valid_attributes
      delete :destroy, {:id => howtolist.to_param}, valid_session
      response.should redirect_to(howtolists_url)
    end
  end

end
